modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/andrew0030/Table-Top-Craft/issues"
logoFile="logo.png"
license="GNU Lesser General Public License v3.0"

[[mods]]
    modId="table_top_craft"
    version="1.19.4-5.0.1"
    displayName="Table Top Craft"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/table-top-craft"
    authors="andrew0030"
    description='''Table Top Craft is a Mod that adds playable table top games to Minecraft.'''

[[dependencies.table_top_craft]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.table_top_craft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"